version: '2'
services:
  db_documents:
    image: postgres
  db_proposals:
    image: postgres
  frontend:
    build:
      context: ./freelance-camp-fe
    command: npm start
    volumes:
      - ./freelance-camp-fe:/app
    ports:
      - "3000:3000"
  backend_documents:
    build:
      context: ./freelance_camp_documents
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:setup && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./freelance_camp_documents:/app
    ports:
      - "3001:3001"
    depends_on:
      - db_documents
  backend_proposals:
    build:
      context: ./freelance_camp_proposal
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:setup && bundle exec rails s -p 3002 -b '0.0.0.0'"
    volumes:
      - ./freelance_camp_proposal:/app
    ports:
      - "3002:3002"
    depends_on:
      - db_proposals
