version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3002:3002"
    depends_on:
      - db
